import { Trade } from "@/types/trade";

// 10 realistic demo trades for non-logged-in users
export const DEMO_TRADES: Trade[] = [
  {
    id: "demo-1",
    createdAt: new Date("2026-01-05"),
    updatedAt: new Date("2026-01-10"),
    symbol: "BTC/USDT",
    type: "BUY",
    quantity: 0.15,
    quantityCurrency: "BTC",
    entryPrice: 42500,
    exitPrice: 44800,
    tradeDate: new Date("2026-01-05"),
    exitDate: new Date("2026-01-10"),
    status: "CLOSED",
    profit: 345,
    profitPercentage: 5.41,
    setupDescription: "Breakout above resistance at 42k with strong volume",
    reasonToBuy: "Double bottom pattern confirmed on 4H chart",
    notes: "Market showed strong bullish momentum after consolidation",
  },
  {
    id: "demo-2",
    createdAt: new Date("2026-01-12"),
    updatedAt: new Date("2026-01-15"),
    symbol: "ETH/USDT",
    type: "BUY",
    quantity: 2.5,
    quantityCurrency: "ETH",
    entryPrice: 2280,
    exitPrice: 2150,
    tradeDate: new Date("2026-01-12"),
    exitDate: new Date("2026-01-15"),
    status: "CLOSED",
    profit: -325,
    profitPercentage: -5.7,
    setupDescription: "Support bounce at 2280 level",
    reasonToBuy: "RSI oversold on daily",
    reasonToSell: "Stop loss hit — support broke down",
    mistakes: "Entered too early before confirmation",
    lessonsLearned: "Wait for confirmation candle before entering",
  },
  {
    id: "demo-3",
    createdAt: new Date("2026-01-20"),
    updatedAt: new Date("2026-01-25"),
    symbol: "SOL/USDT",
    type: "BUY",
    quantity: 25,
    quantityCurrency: "SOL",
    entryPrice: 98.5,
    exitPrice: 112.3,
    tradeDate: new Date("2026-01-20"),
    exitDate: new Date("2026-01-25"),
    status: "CLOSED",
    profit: 345,
    profitPercentage: 14.01,
    setupDescription: "Bull flag on daily chart with increasing volume",
    reasonToBuy: "Strong ecosystem growth and TVL increase",
    notes: "Solana showing relative strength vs market",
  },
  {
    id: "demo-4",
    createdAt: new Date("2026-01-28"),
    updatedAt: new Date("2026-02-02"),
    symbol: "BTC/USDT",
    type: "SELL",
    quantity: 0.1,
    quantityCurrency: "BTC",
    entryPrice: 45200,
    exitPrice: 43800,
    tradeDate: new Date("2026-01-28"),
    exitDate: new Date("2026-02-02"),
    status: "CLOSED",
    profit: 140,
    profitPercentage: 3.1,
    setupDescription: "Rejection at previous high with bearish divergence",
    reasonToBuy: "RSI bearish divergence on 4H timeframe",
    notes: "Short trade — caught the pullback after failed breakout",
  },
  {
    id: "demo-5",
    createdAt: new Date("2026-02-05"),
    updatedAt: new Date("2026-02-10"),
    symbol: "AVAX/USDT",
    type: "BUY",
    quantity: 40,
    quantityCurrency: "AVAX",
    entryPrice: 35.2,
    exitPrice: 38.9,
    tradeDate: new Date("2026-02-05"),
    exitDate: new Date("2026-02-10"),
    status: "CLOSED",
    profit: 148,
    profitPercentage: 10.51,
    setupDescription: "Ascending triangle breakout",
    reasonToBuy: "Volume spike with price above 200 EMA",
  },
  {
    id: "demo-6",
    createdAt: new Date("2026-02-12"),
    updatedAt: new Date("2026-02-14"),
    symbol: "DOGE/USDT",
    type: "BUY",
    quantity: 5000,
    quantityCurrency: "DOGE",
    entryPrice: 0.082,
    exitPrice: 0.076,
    tradeDate: new Date("2026-02-12"),
    exitDate: new Date("2026-02-14"),
    status: "CLOSED",
    profit: -30,
    profitPercentage: -7.32,
    setupDescription: "Momentum play on social media hype",
    reasonToBuy: "Trending on social media with whale activity",
    mistakes: "FOMO entry without proper technical setup",
    lessonsLearned: "Don't chase hype — stick to the plan",
  },
  {
    id: "demo-7",
    createdAt: new Date("2026-02-18"),
    updatedAt: new Date("2026-02-22"),
    symbol: "ETH/USDT",
    type: "BUY",
    quantity: 3,
    quantityCurrency: "ETH",
    entryPrice: 2350,
    exitPrice: 2520,
    tradeDate: new Date("2026-02-18"),
    exitDate: new Date("2026-02-22"),
    status: "CLOSED",
    profit: 510,
    profitPercentage: 7.23,
    setupDescription: "Cup and handle pattern completion on daily",
    reasonToBuy: "ETH/BTC pair showing strength",
    notes: "Clean setup — perfect execution on target",
  },
  {
    id: "demo-8",
    createdAt: new Date("2026-02-25"),
    updatedAt: new Date("2026-03-01"),
    symbol: "LINK/USDT",
    type: "BUY",
    quantity: 100,
    quantityCurrency: "LINK",
    entryPrice: 14.8,
    exitPrice: 16.2,
    tradeDate: new Date("2026-02-25"),
    exitDate: new Date("2026-03-01"),
    status: "CLOSED",
    profit: 140,
    profitPercentage: 9.46,
    setupDescription: "Breakout from range with volume confirmation",
    reasonToBuy: "Partnership announcements and oracle adoption",
  },
  {
    id: "demo-9",
    createdAt: new Date("2026-03-02"),
    updatedAt: new Date("2026-03-04"),
    symbol: "XRP/USDT",
    type: "BUY",
    quantity: 2000,
    quantityCurrency: "XRP",
    entryPrice: 0.62,
    exitPrice: 0.58,
    tradeDate: new Date("2026-03-02"),
    exitDate: new Date("2026-03-04"),
    status: "CLOSED",
    profit: -80,
    profitPercentage: -6.45,
    setupDescription: "Support bounce trade at 0.62",
    reasonToBuy: "Historical support level holding",
    reasonToSell: "Stop loss triggered on market-wide sell-off",
    mistakes: "Didn't account for macro risk — FOMC meeting day",
    lessonsLearned: "Avoid opening trades before major economic events",
  },
  {
    id: "demo-10",
    createdAt: new Date("2026-03-05"),
    updatedAt: new Date("2026-03-05"),
    symbol: "BTC/USDT",
    type: "BUY",
    quantity: 0.2,
    quantityCurrency: "BTC",
    entryPrice: 46200,
    tradeDate: new Date("2026-03-05"),
    status: "OPEN",
    setupDescription: "Breakout above 46k resistance with volume",
    reasonToBuy: "Bullish macro outlook — ETF flows increasing",
    notes: "Targeting 50k with stop at 44.5k",
  },
];

// Pre-computed demo performance metrics based on the 10 trades above
export const DEMO_METRICS = {
  totalTrades: 10,
  closedTrades: 9,
  openTrades: 1,
  winRate: 66.67, // 6 wins out of 9 closed
  totalProfit: 1193,
  bestTrade: 510,
  worstTrade: -325,
  avgProfit: 132.56,
  profitFactor: 3.48, // 1628 / 435
  consecutiveWins: 3,
  consecutiveLosses: 1,
  maxDrawdown: 21.28,
  totalVolume: 7170.45,
};

export const DEMO_MONTHLY_DATA = [
  { month: "2026-01", trades: 4, profit: 505, winRate: 75 },
  { month: "2026-02", trades: 4, profit: 768, winRate: 75 },
  { month: "2026-03", trades: 1, profit: -80, winRate: 0 },
];

export const DEMO_SYMBOL_DATA = [
  { symbol: "ETH/USDT", trades: 2, wins: 1, profit: 185, winRate: 50 },
  { symbol: "BTC/USDT", trades: 2, wins: 2, profit: 485, winRate: 100 },
  { symbol: "SOL/USDT", trades: 1, wins: 1, profit: 345, winRate: 100 },
  { symbol: "AVAX/USDT", trades: 1, wins: 1, profit: 148, winRate: 100 },
  { symbol: "LINK/USDT", trades: 1, wins: 1, profit: 140, winRate: 100 },
  { symbol: "DOGE/USDT", trades: 1, wins: 0, profit: -30, winRate: 0 },
  { symbol: "XRP/USDT", trades: 1, wins: 0, profit: -80, winRate: 0 },
];

export const DEMO_CHART_DATA = [
  { date: "Jan 5", profit: 345, tradeNum: 1 },
  { date: "Jan 15", profit: 20, tradeNum: 2 },
  { date: "Jan 25", profit: 365, tradeNum: 3 },
  { date: "Feb 2", profit: 505, tradeNum: 4 },
  { date: "Feb 10", profit: 653, tradeNum: 5 },
  { date: "Feb 14", profit: 623, tradeNum: 6 },
  { date: "Feb 22", profit: 1133, tradeNum: 7 },
  { date: "Mar 1", profit: 1273, tradeNum: 8 },
  { date: "Mar 4", profit: 1193, tradeNum: 9 },
];

export const DEMO_DRAWDOWN_DATA = [
  { date: "Jan 5", drawdown: 0 },
  { date: "Jan 15", drawdown: 94.20 },
  { date: "Jan 25", drawdown: 0 },
  { date: "Feb 2", drawdown: 0 },
  { date: "Feb 10", drawdown: 0 },
  { date: "Feb 14", drawdown: 4.59 },
  { date: "Feb 22", drawdown: 0 },
  { date: "Mar 1", drawdown: 0 },
  { date: "Mar 4", drawdown: 6.27 },
];

// Demo calculator values
export const DEMO_CALCULATOR = {
  symbol: "BTC/USDT",
  accountBalance: "10000",
  riskPercent: "2",
  entryPrice: "46200",
  takeProfit: "50000",
  leverage: "3",
};
